ecom_app/urls.py
from django.urls import path
from . import views
from django.conf.urls.static import static
from django.conf import settings
app_name = 'ecom_app'

urlpatterns = [
   path('',views.home,name='home'),
   path('shop_register/',views.shop_register,name='shop_register'),
   path('customer_register/',views.customer_register,name='customer_register'),
   path('ecom_login/',views.ecom_login,name='ecom_login'),
   path('ecom_logout/',views.ecom_logout,name='ecom_logout'),
]

ecom_pro/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('ecom_app.urls')),
    path('shop/',include('shop_app.urls')),
    path('customer/',include('customer_app.urls')),
    
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop_app/urls.py
from django.urls import path
from . import views
from django.conf.urls.static import static
from django.conf import settings
app_name = 'shop_app'

urlpatterns = [
  path('',views.demo,name='demo'),
  path('shop_info/',views.shop_info.as_view(),name='shop_info'),
  path('product_list/',views.product_list.as_view(),name='product_list'),
  path('product_update/<int:pk>',views.product_update.as_view(),name ='product_update'),
  path('product_delete/<int:pk>',views.product_delete.as_view(),name ='product_delete'),
  path('product_details/<int:pk>',views.product_details.as_view(),name ='product_details'),
  
]

shop_app/models.py
from django.db import models
from ecom_app.models import *
from django.conf import settings

class shop_items(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.CASCADE)
    product_name = models.CharField(max_length = 20)
    product_price = models.IntegerField()
    product_brand = models.CharField(max_length = 30)
    product_image = models.ImageField(upload_to ='shop')
    
    def __str__(self):
        return  f'{self.user.get_full_name()},{self.product_name}'

shop_app/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.http import Http404,HttpResponse
from django.views.generic.edit import CreateView,UpdateView,DeleteView
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.contrib.auth.mixins import LoginRequiredMixin,UserPassesTestMixin
from django.contrib.auth.decorators import login_required
from .models import shop_items
from ecom_app.models import UserProfile


@login_required
def demo(request):
    return HttpResponse("hello shop_owner")


class shop_info(LoginRequiredMixin,UserPassesTestMixin,CreateView):
    model = shop_items
    fields = ['product_name','product_price','product_brand','product_image']

    success_url = reverse_lazy('shop_app:product_list')

    def form_valid(self, form):
        form.instance.user=self.request.user
        return super(shop_info,self).form_valid(form)
    
    def test_func(self):
        x = self.request.user
        if x.is_shop:
            return True
        else:
            raise
        Http404('you are not allowed here')

class product_list(LoginRequiredMixin,UserPassesTestMixin,ListView):
    model = shop_items
    
    def get_context_data(self,  **kwargs):
        context=super().get_context_data( **kwargs)
        context['object_list']=context['object_list'].filter(user = self.request.user)
        return context
    
    def test_func(self):
        x = self.request.user
        if x.is_shop:
            return True
        else:
            raise
        Http404('you are not allowed here')

class product_update(LoginRequiredMixin,UserPassesTestMixin,UpdateView):
    model = shop_items
    fields = ['product_name','product_price','product_brand','product_image']
    success_url = reverse_lazy('shop_app:product_list')

    def test_func(self):
        x = self.request.user
        if x.is_shop:
            return True
        else:
            raise
        Http404('you are not allowed here')



class product_delete(LoginRequiredMixin,UserPassesTestMixin,DeleteView):
    model = shop_items
    context_object_name = 'task'
    success_url = reverse_lazy('shop_app:product_list')

    def test_func(self):
        x = self.request.user
        if x.is_shop:
            return True
        else:
            raise
        Http404('you are not allowed here')

class product_details(LoginRequiredMixin,UserPassesTestMixin,DetailView):
    model = shop_items
    context_object_name = 'top'

    def test_func(self):
        x = self.request.user
        if x.is_shop:
            return True
        else:
            raise
        Http404('you are not allowed here')

###############################################################







    

templates/shop_app/shop_base.html
<!doctype html>
<html lang="en">

  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Font Awesome -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css" rel="stylesheet"/>
    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap" rel="stylesheet"/>
    <!-- MDB -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/3.3.0/mdb.min.css" rel="stylesheet"/>
  

      
    <title>ecom_pro</title>
  </head>
  <body>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <!-- Container wrapper -->
  <div class="container-fluid">
      <a class="navbar-brand" href="#">E-COM</a>
    <!-- Toggle button -->
    <button
      class="navbar-toggler"
      type="button"
      data-mdb-toggle="collapse"
      data-mdb-target="#navbarLeftAlignExample"
      aria-controls="navbarLeftAlignExample"
      aria-expanded="false"
      aria-label="Toggle navigation"
    >
      <i class="fas fa-bars"></i>
    </button>

    <!-- Collapsible wrapper -->
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <!-- Left links -->
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active abc" aria-current="page" href="{% url 'shop_app:shop_info' %}">product_create</a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" href="{% url 'shop_app:product_list' %}">product_index</a>
        </li>
         <li class="nav-item ">
          <a class="nav-link active" style="margin-left: 450px;" href="{% url 'ecom_app:ecom_logout' %}">Logout</a>
        </li>

      </ul>
      <!-- Left links -->

    </div>
    <!-- Collapsible wrapper -->
  </div>
  <!-- Container wrapper -->
</nav>


{% if messages %}

    {% for message in messages %}
    <div class="alert alert-warning alert-dismissible fade show" role="alert">
    {{ message }}
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
    {% endfor %}

{% endif %}
      {% block body %}
      {% endblock %}



<!-- MDB -->
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/3.3.0/mdb.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js" integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf" crossorigin="anonymous"></script>
  </body>
</html>

templates/shop_app/shop_items_confirm_delete.html
<body>
<form method="post">
    {% csrf_token %}
      <div class="toast">
        <div class="toast-header">
        </div>
          <div class="toast-body">
            Are You really want to delete this product? <br>
            <input type="submit" value="Delete">
           <a href="{% url 'shop_app:product_list' %}">No</a>
          </div>
        </div>
        
</form>
</body>

templates/shop_app/shop_items_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{{top.id}}<br>
{{ top.product_name }}<br>
{{ top.product_price }}<br>
{{ top.product_brand }}<br>
{{ top.product_image }}<br>

</body>
</html>

templates/shop_app/shop_items_form.html
{% extends 'shop_app/shop_base.html' %}
{% block body %}
    <div class="container p-5 mt-5 border">
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <center><button type="submit" class="btn btn-sm btn-primary">ADD_TO_PRODUCT</button></center>
        </form>
    </div>
{% endblock %}

templates/shop_app/shop_items_list.html
{% extends 'shop_app/shop_base.html' %}
{% block body %}

<div class="container">
  <hr>
  <h2>Product_index</h2>
          
  <table class="table table-hover">
    <thead>
      <tr>
        <th>sr.no</th>
        <th>product_name</th>
        <th>product_price</th>
        <th>product_brand</th>
        <th>product_image</th>
        <th>actions</th>
      </tr>
    </thead>
    <tbody>
           {% for i in object_list %}
           <tr>
               <th>{{ forloop.counter }}</th>
               <td>{{ i.product_name }}</td>
               <td>{{ i.product_price }}</td>
               <td>{{ i.product_brand }}</td>
               <td>{{ i.product_image }}</td>
               <td><a href="{% url 'shop_app:product_update' i.id %}"class='btn btn-sm btn-primary'>EDIT</a></td>
               <td><a href="{% url 'shop_app:product_delete' i.id %}"class='btn btn-sm btn-primary'>DELETE</a></td>
               <td><a href="{% url 'shop_app:product_details' i.id %}"class='btn btn-sm btn-primary'>DETAILS</a></td>
           </tr>
           {% endfor %}
    </tbody>
  </table>
</div>
{% endblock %}