customer_app/urls.py
from django.urls import path
from . import views
from django.conf.urls.static import static
from django.conf import settings
app_name = 'customer_app'

urlpatterns = [
  path('',views.demo,name='demo'),
  path('add_to_cart/<int:id>',views.add_to_cart,name='add_to_cart'),
  path('cart_details/',views.cart_details.as_view(),name ='cart_details'),
  path('product_list_show/',views.product_list_show.as_view(),name='product_list_show'),
  path('order_summery', views.OrderSummeryView.as_view(), name='order_summery'),
  path('remove_single_item_cart/<int:id>', views.remove_single_item_from_cart, name='remove_single_item_cart')
  
]

ecom_app/urls.py
from django.urls import path
from . import views
from django.conf.urls.static import static
from django.conf import settings
app_name = 'ecom_app'

urlpatterns = [
   path('',views.home,name='home'),
   path('shop_register/',views.shop_register,name='shop_register'),
   path('customer_register/',views.customer_register,name='customer_register'),
   path('ecom_login/',views.ecom_login,name='ecom_login'),
   path('ecom_logout/',views.ecom_logout,name='ecom_logout'),
]

ecom_pro/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('ecom_app.urls')),
    path('shop/',include('shop_app.urls')),
    path('customer/',include('customer_app.urls')),
    
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

customer_app/models.py
from django.db import models
from django.core.validators import RegexValidator
from shop_app.models import shop_items
from django.conf import settings

# Create your models here.

class OrderItem(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    Product = models.ForeignKey(shop_items, on_delete=models.CASCADE)
    ordered = models.BooleanField(default=False)
    quntity = models.IntegerField(default=1)
    

    def __str__(self):
        return self.Product.product_name

    def get_total_item_price(self):
        return self.quntity * self.Product.product_price
    
    
class Order(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    item = models.ManyToManyField(OrderItem)
    start_date = models.DateTimeField(auto_now_add=True)
    ordered_date = models.DateTimeField()
    ordered = models.BooleanField(default=False)

    def __str__(self):
        return self.user.first_name
    
    def gst_total(self):
        total = 0
        for i in self.item.all():
            total += i.get_total_item_price()
      
        gst = (total*18)/100
        cgst = (total*18)/100
        net_price = total+gst
        if net_price < 0:
            net_price = 0
        else:
            net_price = net_price
        return round(net_price)

    def get_total(self):
        total = 0
        for i in self.item.all():
            total += i.get_total_item_price()
        return total
    
  

customer_app/views.py
from django.shortcuts import get_object_or_404, redirect, render
from shop_app.models import shop_items
from django.contrib import messages
from django.utils import timezone
from django.http import HttpResponse
from django.views.generic.list import ListView
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import *
from django.views import View
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import ObjectDoesNotExist

# Create your views here.

def demo(request):
    return HttpResponse("hello customer")

class product_list_show(LoginRequiredMixin,ListView):
    model = shop_items
    template_name = 'customer_app/shop_items_list_show.html'
    
    def get_context_data(self,**kwargs):
        context=super().get_context_data( **kwargs)
        context['object_list']=context['object_list'].all()
        return context

def add_to_cart(request, id):
    item = get_object_or_404(shop_items, id=id)
    order_item, created = OrderItem.objects.get_or_create(Product=item, user=request.user, ordered=False)
    order_qs = Order.objects.filter(user=request.user, ordered=False)
    if order_qs .exists():
        order = order_qs[0] 
        if order.item.filter(Product_id=item.pk).exists():
            order_item.quntity += 1
            order_item.save()
            messages.info(request, "Item Quantity was updated.")
            return redirect('customer_app:product_list_show')
        else:
            messages.info(request, "Item was added to a cart.")
            order.item.add(order_item)
            return redirect('customer_app:product_list_show')
    else:
        ordered_date = timezone.now()
        order = Order.objects.create(user=request.user, ordered_date=ordered_date)
        order.item.add(order_item)
        messages.info(request, "Item was added to a cart.")
    return redirect('customer_app:product_list_show')

class cart_details(LoginRequiredMixin,View):
    def get(self, *args, **kwargs):
        try:
            order = Order.objects.get(user=self.request.user, ordered=False)
            context = {'object': order}
            return render(self.request, 'customer_app/cart_details.html', context=context)
        except ObjectDoesNotExist:
            return redirect('customer_app:product_list_show')
   


######################################################################################################

def remove_from_cart(request, id):
    item = get_object_or_404(shop_items, id=id)
    order_qs = Order.objects.filter(user=request.user, ordered=False)
    if order_qs.exists():
        order = order_qs[0]
        if order.item.filter(Product_id=item.pk).exists():
            order_item = OrderItem.objects.filter(Product=item, user=request.user, ordered=False)[0]
            order.item.model.delete(order_item)
            messages.info(request, "Item was removed from cart")
            return redirect("customer_app:product_list_show")
        else:
            messages.info(request, "Item was not in your cart")
            return redirect("customer_app:product_list_show")
    else:
        messages.info(request, "You do not have active order")
        return redirect("customer_app:product_list_show")

def remove_single_item_from_cart(request, id):
    item = get_object_or_404(shop_items, id=id)
    order_qs = Order.objects.filter(user=request.user, ordered=False)
    if order_qs.exists():
        order = order_qs[0]
        if order.item.filter(Product_id=item.pk).exists():
            order_item = OrderItem.objects.filter(Product=item, user=request.user, ordered=False)[0]
            if order_item.quntity > 1:
                order_item.quntity -= 1
                order_item.save()
                messages.info(request, "Item Quantity Updated")
                return redirect("customer_app:order_summery")
            else:
                order.item.model.delete(order_item)
            messages.info(request, "Item was removed from cart")
            return redirect("customer_app:product_list_show")
        else:
            messages.info(request, "Item was not in your cart")
            return redirect("customer_app:product_list_show")
    else:
        messages.info(request, "You do not have active order")
        return redirect("customer_app:product_list_show")


class OrderSummeryView(LoginRequiredMixin, View):
    def get(self, *args, **kwargs):
        try:
            order = Order.objects.get(user=self.request.user, ordered=False)
            context = {'object': order}
            return render(self.request, 'customer_app/order_summery.html', context=context)
        except ObjectDoesNotExist:
            return redirect('customer_app:product_list_show')

templates/customer_app/cart_details.html
<!-- <div class="modal" tabindex="-1">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title">Modal title</h5>
          <p>Modal body text goes here.</p>
          <button
            type="button"
            class="btn-close"
            data-mdb-dismiss="modal"
            aria-label="Close"
          ></button>
        </div>
        <div class="modal-body">
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-mdb-dismiss="modal">
            Close
          </button>
          <button type="button" class="btn btn-primary"><a href="{% url 'customer_app:order_summery' %}"> order_summery</a></button>
        </div>
      </div>
    </div>
  </div> -->

<!DOCTYPE html>
{% load cart_templates_tags %} 
  <html lang="en">
  <head>
    <title>Bootstrap Example</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
  </head>
  <body>

  <div class="container">
   <!-- Modal content-->
        <div class="modal-content">
          <div class="modal-header">
            <a href="{% url 'customer_app:product_list_show' %}" class="close"  data-dismiss="modal">&times;</a> </button>
            <center><h4 class="modal-title">YOUR SELECTED ITEMS         <span style="color: red;">{{ request.user|cart_item_count }}</span></h4></center>
          </div>
          <div class="modal-body">
            <tbody>
                {% for i in object.item.all %}
               
                <tr>
                    <th>{{ forloop.counter }}</th><br>
                    <td>{{ i.Product.product_name }}</td><br>
                    <td>{{ i.Product.product_price }}</td><br>
                    <td>{{ i.Product.product_brand }}</td><br>
                    <td><img src="{{ i.Product.product_image.url}}" alt="images" width="50",height="50"></td><br><br>
                </tr>
            
                {% endfor %}
           </tbody>

            
          </div>
           <div class="modal-footer">
            <center><a href="{% url 'customer_app:order_summery' %}"class='btn btn-primary'>ORDER_SUMMERY</a></center>
          </div>
        </div>
        
      </div>
    </div>
    
  </div>
  <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/3.3.0/mdb.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js" integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf" crossorigin="anonymous"></script>
</body>
</html>

templates/customer_app/customer_base.html
<!doctype html>
{% load cart_templates_tags %}
<html lang="en">

  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Font Awesome -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css" rel="stylesheet"/>
    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap" rel="stylesheet"/>
    <!-- MDB -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/3.3.0/mdb.min.css" rel="stylesheet"/>
  

      
    <title>ecom_pro</title>
  </head>
  <body>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <!-- Container wrapper -->
  <div class="container-fluid">
      <a class="navbar-brand" href="#">E-COM</a>
    <!-- Toggle button -->
    <button
      class="navbar-toggler"
      type="button"
      data-mdb-toggle="collapse"
      data-mdb-target="#navbarLeftAlignExample"
      aria-controls="navbarLeftAlignExample"
      aria-expanded="false"
      aria-label="Toggle navigation"
    >
      <i class="fas fa-bars"></i>
    </button>

    <!-- Collapsible wrapper -->
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <!-- Left links -->
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" href="{% url 'customer_app:product_list_show' %}">CUSTOMER_INDEX</a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" href="{% url 'customer_app:cart_details' %}">CART <span style="color: red;">{{ request.user|cart_item_count }}</span> </a>
        </li>
        
         <li class="nav-item ">
          <a class="nav-link active" style="margin-left: 450px;" href="{% url 'ecom_app:ecom_logout' %}">LOGOUT</a>
        </li>

      </ul>
      <!-- Left links -->

    </div>
    <!-- Collapsible wrapper -->
  </div>
  <!-- Container wrapper -->
</nav>


{% if messages %}

    {% for message in messages %}
    <div class="alert alert-warning alert-dismissible fade show" role="alert">
    {{ message }}
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
    {% endfor %}

{% endif %}
      {% block body %}
      {% endblock %}



<!-- MDB -->
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/3.3.0/mdb.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js" integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf" crossorigin="anonymous"></script>
  </body>
</html>

templates/customer_app/order_summery.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Bootstrap Example</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
  </head>
<body>
    
 <div class="container">
    <!-- Modal content-->
        <div class="modal-content">
          <div class="modal-header">
            <center><h4 class="modal-title">SHOP_ITEMS </h4></center>
          </div>
          <div class="modal-body">
                <table class="table table-hover">
                  <tr>
                      <thead>
                      <th>sr.no</th>
                      <th>product_name</th>
                      <th>product_price</th>
                      <th>product_brand</th>
                      <th>Totla Price</th>
                   
                      <th>product_image</th>
                      <th>actions</th>
                    </tr>
                  </thead>
                  <tbody>
                        {% for i in object.item.all %}
                        <tr>
                            <th>{{ forloop.counter }}</th>
                            <td>{{ i.Product.product_name }}</td>
                            <td>{{ i.Product.product_price }}</td>
                            <td>{{ i.Product.product_brand }}</td>
                            <td>{{ i.get_total_item_price }}</td>
                          
                            <td><img src="{{ i.Product.product_image.url}}" alt="images" width="50",height="50"></td>
                            <td><a href="{% url 'customer_app:add_to_cart' i.Product.id %}">+</a> {{ i.quntity }} <a href="{% url 'customer_app:remove_single_item_cart' i.Product.id %}">-</a></td>
                            
                          </tr>
                        {% endfor %}

                      </tbody>
                    </table>
                    <tr>
                     <b>Grand Total = <span style="color: orangered;">{{ object.gst_total }}(with tax%)</span></b> <br>
                      <b>Orignal Price = <span style="color: orangered;">{{ object.get_total }}</span></b>
                    </tr>
      
              </div>
            </div>
   
    </div> 
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/3.3.0/mdb.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js" integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf" crossorigin="anonymous"></script> 
</body>
</html>

templates/customer_app/shop_items_list_show.html
{% extends 'customer_app/customer_base.html' %}

{% block body %}


  <hr>
 <center><h2>SHOP-ITEMS</h2></center> <br>
          
  <table class="table table-hover">
    <thead>
      <tr>
        <th>sr.no</th>
        <th>product_name</th>
        <th>product_price</th>
        <th>product_brand</th>
        <th>product_image</th>
        <th>actions</th>
      </tr>
    </thead>
    <tbody>
           {% for i in object_list %}
           <tr>
               <th>{{ forloop.counter }}</th>
               <td>{{ i.product_name }}</td>
               <td>{{ i.product_price }}</td>
               <td>{{ i.product_brand }}</td>
               <td><img src="{{ i.product_image.url}}" alt="images" width ="50",height ="50"></td>
               <td><a href="{% url 'customer_app:add_to_cart' i.id %}"class='btn btn-sm btn-primary'>add cart</a></td>
            </tr>
           {% endfor %}
    </tbody>
  </table>
</div>
{% endblock %}