ecom_app/urls.py
from django.urls import path
from . import views
from django.conf.urls.static import static
from django.conf import settings
app_name = 'ecom_app'

urlpatterns = [
   path('',views.home,name='home'),
   path('shop_register/',views.shop_register,name='shop_register'),
   path('customer_register/',views.customer_register,name='customer_register'),
   path('ecom_login/',views.ecom_login,name='ecom_login'),
   path('ecom_logout/',views.ecom_logout,name='ecom_logout'),
]

ecom_pro/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('ecom_app.urls')),
    path('shop/',include('shop_app.urls')),
    path('customer/',include('customer_app.urls')),
    
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
<!doctype html>
<html lang="en">

  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Font Awesome -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css" rel="stylesheet"/>
    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap" rel="stylesheet"/>
    <!-- MDB -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/3.3.0/mdb.min.css" rel="stylesheet"/>
  

      
    <title>ecom_pro</title>
  </head>
  <body>
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <!-- Container wrapper -->
  <div class="container-fluid">
      <a class="navbar-brand" href="#">E-COM</a>
    <!-- Toggle button -->
    <button
      class="navbar-toggler"
      type="button"
      data-mdb-toggle="collapse"
      data-mdb-target="#navbarLeftAlignExample"
      aria-controls="navbarLeftAlignExample"
      aria-expanded="false"
      aria-label="Toggle navigation"
    >
      <i class="fas fa-bars"></i>
    </button>

    <!-- Collapsible wrapper -->
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <!-- Left links -->
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active abc" aria-current="page" href="{% url 'ecom_app:shop_register' %}">Shop Registration</a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" href="{% url 'ecom_app:customer_register' %}">Customer Registration</a>
        </li>
         <li class="nav-item">
          <a class="nav-link active" href="{% url 'ecom_app:ecom_login' %}">Login</a>
        </li>
         <li class="nav-item ">
          <a class="nav-link active" style="margin-left: 450px;" href="{% url 'ecom_app:ecom_logout' %}">Logout</a>
        </li>

      </ul>
      <!-- Left links -->

    </div>
    <!-- Collapsible wrapper -->
  </div>
  <!-- Container wrapper -->
</nav>


{% if messages %}

    {% for message in messages %}
    <div class="alert alert-warning alert-dismissible fade show" role="alert">
    {{ message }}
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
    {% endfor %}

{% endif %}
      {% block body %}
      {% endblock %}



<!-- MDB -->
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/3.3.0/mdb.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js" integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf" crossorigin="anonymous"></script>
  </body>
</html>